name: 'kiipo_action_toggle_workflow'
description: 'enable or disable a github workflow'
inputs:
  workflow_filename:
    description: 'optional filename of the workflow to disable'
  github_token:
    required: true 
    description: 'octokit token'
  enable_or_disable:
    required: true 
    description: 'put "enable" or "disable"'
outputs:
  version:
    description: 'new version of the package'
runs:
  using: 'node12'
  main: 'build/index.js'
